FROM ghcr.io/puppeteer/puppeteer:24.1.1

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=false

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm ci && node node_modules/puppeteer/install.js

COPY . .

# Comando para rodar a aplicação
CMD ["npm", "run", "dev"]
