FROM ghcr.io/puppeteer/puppeteer:24.1.1

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=false

WORKDIR /usr/src/app

COPY package*.json ./

# Primeiro, instala dependências do projeto
RUN npm install

# Em seguida, instala o Chromium manualmente
RUN npx puppeteer install

COPY . .

# Comando para rodar a aplicação
CMD ["npm", "run", "dev"]
